### ISSUE TITLE
[Feature request] Hints when missing export folder

### ISSUE THREAD

**Issue by tai271828** [pycontw/talk-preview-img-builder#3]
By default the tool exports images/ppt to `export` folder. The folder needs to be created prior to using this tool, otherwise `FileNotFoundError: [Errno 2] No such file or directory`.

**Describe the solution you'd like**
`try-except` should be sufficient.

**Describe alternatives you've considered**
Prompt for interactive input

**Additional context**
Test version: f1c1c7037709b1adb064bb67e6290d5179d5770f
Python 3.8.5

**Comment by josix** [comment]
Resolved by #5
